spring.application.name=developer-growth-tracker
spring.datasource.url=jdbc:mysql://localhost:3306/developer_growth_tracker
spring.datasource.username=root
spring.datasource.password=@Moksha03

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true